FROM arm64v8/node:17.8.0-alpine3.15

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn workspace @parca/web install

EXPOSE 3000

CMD yarn workspace @parca/web dev
